### ISSUE TITLE
Omniauth поидее не  используется...

### ISSUE THREAD

**Issue by sars** [Miroshni4enko/AuctionMarketplace#15]
https://github.com/Miroshni4enko/AuctionMarketplace/blob/5e4cb7d81cf16cfbd4f4c40f5cbfb5787ee0d77a/app/models/user.rb#L14

**Comment by Miroshni4enko** [comment]
done https://github.com/Miroshni4enko/AuctionMarketplace/commit/b950a28b2f57cdff7e6000e7684ec849b2091420
